name: ci

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with: 
          python-version: "3.11"
          
      - name: Install dependencies
        run: |
          pip install -r api/requirements.txt
          pip install pytest httpx pytest-asyncio ruff
          
      - name: Lint with ruff (warn-only)
        run: |
          ruff check app/ || true  # warn-only; don't block you
          
      - name: Run smoke tests
        run: |
          pytest tests/test_smoke.py -q || true  # warn-only; flip to hard-fail later
          
      - name: Security check - no hardcoded secrets
        run: |
          # Simple check for common secrets patterns
          if grep -r "ANTHROPIC_API_KEY.*=" app/ || grep -r "sk-" app/ || grep -r "password.*=" app/; then
            echo "❌ Potential secrets found in code"
            exit 1
          fi
          echo "✅ No obvious secrets found"